#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
#  icon_wall.py
"""
Frame to show all of the stock art resources
"""
#
#  Copyright 2020 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# generated by wxGlade 0.9.3 on Tue Apr  7 09:14:58 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


ArtClients = ["wx.ART_TOOLBAR",
              "wx.ART_MENU",
              "wx.ART_FRAME_ICON",
              "wx.ART_CMN_DIALOG",
              "wx.ART_HELP_BROWSER",
              "wx.ART_MESSAGE_BOX",
              "wx.ART_OTHER",
              ]


class IconWall(wx.Frame):
    def __init__(self, *args, **kwds):
        self.client = wx.ART_TOOLBAR
        self.icon_size = 64
        # begin wxGlade: IconWall.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.client_combo = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.size_spinctrl = wx.SpinCtrl(self, wx.ID_ANY, "64", min=16, max=256, style=wx.SP_ARROW_KEYS | wx.TE_PROCESS_ENTER)
        self.wx_ART_ERROR = IconPanel(self, "wx.ART_ERROR", wx.ART_ERROR, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_QUESTION = IconPanel(self, "wx.ART_QUESTION", wx.ART_QUESTION, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_WARNING = IconPanel(self, "wx.ART_WARNING", wx.ART_WARNING, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_INFORMATION = IconPanel(self, "wx.ART_INFORMATION", wx.ART_INFORMATION, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_ADD_BOOKMARK = IconPanel(self, "wx.ART_ADD_BOOKMARK", wx.ART_ADD_BOOKMARK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_DEL_BOOKMARK = IconPanel(self, "wx.ART_DEL_BOOKMARK", wx.ART_DEL_BOOKMARK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP_SIDE_PANEL = IconPanel(self, "wx.ART_HELP_SIDE_PANEL", wx.ART_HELP_SIDE_PANEL, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP_SETTINGS = IconPanel(self, "wx.ART_HELP_SETTINGS", wx.ART_HELP_SETTINGS, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP_BOOK = IconPanel(self, "wx.ART_HELP_BOOK", wx.ART_HELP_BOOK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP_FOLDER = IconPanel(self, "wx.ART_HELP_FOLDER", wx.ART_HELP_FOLDER, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP_PAGE = IconPanel(self, "wx.ART_HELP_PAGE", wx.ART_HELP_PAGE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_BACK = IconPanel(self, "wx.ART_GO_BACK", wx.ART_GO_BACK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_FORWARD = IconPanel(self, "wx.ART_GO_FORWARD", wx.ART_GO_FORWARD, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_UP = IconPanel(self, "wx.ART_GO_UP", wx.ART_GO_UP, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_DOWN = IconPanel(self, "wx.ART_GO_DOWN", wx.ART_GO_DOWN, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_TO_PARENT = IconPanel(self, "wx.ART_GO_TO_PARENT", wx.ART_GO_TO_PARENT, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_HOME = IconPanel(self, "wx.ART_GO_HOME", wx.ART_GO_HOME, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GOTO_FIRST = IconPanel(self, "wx.ART_GOTO_FIRST", wx.ART_GOTO_FIRST, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GOTO_LAST = IconPanel(self, "wx.ART_GOTO_LAST", wx.ART_GOTO_LAST, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_PRINT = IconPanel(self, "wx.ART_PRINT", wx.ART_PRINT, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HELP = IconPanel(self, "wx.ART_HELP", wx.ART_HELP, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_TIP = IconPanel(self, "wx.ART_TIP", wx.ART_TIP, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_REPORT_VIEW = IconPanel(self, "wx.ART_REPORT_VIEW", wx.ART_REPORT_VIEW, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_LIST_VIEW = IconPanel(self, "wx.ART_LIST_VIEW", wx.ART_LIST_VIEW, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_NEW_DIR = IconPanel(self, "wx.ART_NEW_DIR", wx.ART_NEW_DIR, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FOLDER = IconPanel(self, "wx.ART_FOLDER", wx.ART_FOLDER, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FOLDER_OPEN = IconPanel(self, "wx.ART_FOLDER_OPEN", wx.ART_FOLDER_OPEN, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_GO_DIR_UP = IconPanel(self, "wx.ART_GO_DIR_UP", wx.ART_GO_DIR_UP, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_EXECUTABLE_FILE = IconPanel(self, "wx.ART_EXECUTABLE_FILE", wx.ART_EXECUTABLE_FILE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_NORMAL_FILE = IconPanel(self, "wx.ART_NORMAL_FILE", wx.ART_NORMAL_FILE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_TICK_MARK = IconPanel(self, "wx.ART_TICK_MARK", wx.ART_TICK_MARK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_CROSS_MARK = IconPanel(self, "wx.ART_CROSS_MARK", wx.ART_CROSS_MARK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_MISSING_IMAGE = IconPanel(self, "wx.ART_MISSING_IMAGE", wx.ART_MISSING_IMAGE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_NEW = IconPanel(self, "wx.ART_NEW", wx.ART_NEW, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FILE_OPEN = IconPanel(self, "wx.ART_FILE_OPEN", wx.ART_FILE_OPEN, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FILE_SAVE = IconPanel(self, "wx.ART_FILE_SAVE", wx.ART_FILE_SAVE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FILE_SAVE_AS = IconPanel(self, "wx.ART_FILE_SAVE_AS", wx.ART_FILE_SAVE_AS, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_DELETE = IconPanel(self, "wx.ART_DELETE", wx.ART_DELETE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_COPY = IconPanel(self, "wx.ART_COPY", wx.ART_COPY, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_CUT = IconPanel(self, "wx.ART_CUT", wx.ART_CUT, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_PASTE = IconPanel(self, "wx.ART_PASTE", wx.ART_PASTE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_UNDO = IconPanel(self, "wx.ART_UNDO", wx.ART_UNDO, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_REDO = IconPanel(self, "wx.ART_REDO", wx.ART_REDO, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_PLUS = IconPanel(self, "wx.ART_PLUS", wx.ART_PLUS, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_MINUS = IconPanel(self, "wx.ART_MINUS", wx.ART_MINUS, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_CLOSE = IconPanel(self, "wx.ART_CLOSE", wx.ART_CLOSE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_QUIT = IconPanel(self, "wx.ART_QUIT", wx.ART_QUIT, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FIND = IconPanel(self, "wx.ART_FIND", wx.ART_FIND, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FIND_AND_REPLACE = IconPanel(self, "wx.ART_FIND_AND_REPLACE", wx.ART_FIND_AND_REPLACE, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_HARDDISK = IconPanel(self, "wx.ART_HARDDISK", wx.ART_HARDDISK, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_FLOPPY = IconPanel(self, "wx.ART_FLOPPY", wx.ART_FLOPPY, self.icon_size, self.client, wx.ID_ANY)
        self.wx_ART_CDROM = IconPanel(self, "wx.ART_CDROM", wx.ART_CDROM, self.icon_size, self.client, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.on_select_client, self.client_combo)
        self.Bind(wx.EVT_SPINCTRL, self.on_select_size, self.size_spinctrl)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_select_size, self.size_spinctrl)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: IconWall.__set_properties
        self.SetTitle("frame")
        # end wxGlade
        for client in ArtClients:
            self.client_combo.Append(client)
        self.client_combo.Select(0)

    def __do_layout(self):
        # begin wxGlade: IconWall.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(11, 5, 0, 0)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        client_label = wx.StaticText(self, wx.ID_ANY, "Client: ")
        sizer_3.Add(client_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.client_combo, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        size_label = wx.StaticText(self, wx.ID_ANY, "Size: ")
        sizer_3.Add(size_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.size_spinctrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_ERROR, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_QUESTION, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_WARNING, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_INFORMATION, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_ADD_BOOKMARK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_DEL_BOOKMARK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP_SIDE_PANEL, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP_SETTINGS, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP_BOOK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP_FOLDER, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP_PAGE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_BACK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_FORWARD, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_UP, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_DOWN, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_TO_PARENT, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_HOME, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GOTO_FIRST, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GOTO_LAST, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_PRINT, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HELP, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_TIP, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_REPORT_VIEW, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_LIST_VIEW, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_NEW_DIR, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FOLDER, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FOLDER_OPEN, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_GO_DIR_UP, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_EXECUTABLE_FILE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_NORMAL_FILE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_TICK_MARK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_CROSS_MARK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_MISSING_IMAGE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_NEW, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FILE_OPEN, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FILE_SAVE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FILE_SAVE_AS, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_DELETE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_COPY, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_CUT, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_PASTE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_UNDO, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_REDO, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_PLUS, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_MINUS, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_CLOSE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_QUIT, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FIND, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FIND_AND_REPLACE, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_HARDDISK, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_FLOPPY, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.wx_ART_CDROM, 1, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def on_select_client(self, event):  # wxGlade: IconWall.<event_handler>
        self.client = eval(event.GetString())
        self.getArt()
    
    def getArt(self):
     for widget in {
             self.wx_ART_ERROR, self.wx_ART_QUESTION, self.wx_ART_WARNING, self.wx_ART_INFORMATION,
             self.wx_ART_ADD_BOOKMARK, self.wx_ART_DEL_BOOKMARK, self.wx_ART_HELP_SIDE_PANEL,
             self.wx_ART_HELP_SETTINGS, self.wx_ART_HELP_BOOK, self.wx_ART_HELP_FOLDER,
             self.wx_ART_HELP_PAGE, self.wx_ART_GO_BACK, self.wx_ART_GO_FORWARD, self.wx_ART_GO_UP,
             self.wx_ART_GO_DOWN, self.wx_ART_GO_TO_PARENT, self.wx_ART_GO_HOME, self.wx_ART_GOTO_FIRST,
             self.wx_ART_GOTO_LAST, self.wx_ART_PRINT, self.wx_ART_HELP, self.wx_ART_TIP,
             self.wx_ART_REPORT_VIEW, self.wx_ART_LIST_VIEW, self.wx_ART_NEW_DIR, self.wx_ART_FOLDER,
             self.wx_ART_FOLDER_OPEN, self.wx_ART_GO_DIR_UP, self.wx_ART_EXECUTABLE_FILE,
             self.wx_ART_NORMAL_FILE, self.wx_ART_TICK_MARK, self.wx_ART_CROSS_MARK,
             self.wx_ART_MISSING_IMAGE, self.wx_ART_NEW, self.wx_ART_FILE_OPEN, self.wx_ART_FILE_SAVE,
             self.wx_ART_FILE_SAVE_AS, self.wx_ART_DELETE, self.wx_ART_COPY, self.wx_ART_CUT,
             self.wx_ART_PASTE, self.wx_ART_UNDO, self.wx_ART_REDO, self.wx_ART_PLUS, self.wx_ART_MINUS,
             self.wx_ART_CLOSE, self.wx_ART_QUIT, self.wx_ART_FIND, self.wx_ART_FIND_AND_REPLACE,
             self.wx_ART_HARDDISK, self.wx_ART_FLOPPY, self.wx_ART_CDROM,
             }:
         widget.client = self.client
         widget.icon_size = self.icon_size
         widget.Refresh()
        
    def on_select_size(self, event):  # wxGlade: IconWall.<event_handler>
        self.icon_size = int(event.GetString())
        self.getArt()
        
# end of class IconWall


class IconPanel(wx.Panel):
    def __init__(self, parent, icon_name, icon_id, icon_size, art_client, *args, **kwds):
        args = (parent, *args)
        # begin wxGlade: IconPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.icon = wx.StaticBitmap(self, wx.ID_ANY, wx.NullBitmap)
        self.caption = wx.StaticText(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.icon_size = icon_size
        self.icon_id = icon_id
        self.art_client = art_client
        
        self.Refresh()
        self.caption.SetLabel(icon_name)

    def __set_properties(self):
        # begin wxGlade: IconPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: IconPanel.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.icon, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.caption, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
    
    def Refresh(self, eraseBackground=True, rect=None):
        self.icon.SetBitmap(wx.ArtProvider.GetBitmap(self.icon_id, self.art_client, wx.Size(self.icon_size, self.icon_size)))
        self.Layout()
        wx.Panel.Refresh(self, eraseBackground, rect)
    

# end of class IconPanel

class IconWallApp(wx.App):
    def OnInit(self):
        self.frame = IconWall(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class IconWallApp


if __name__ == "__main__":
    icon_wall_app = IconWallApp(0)
    icon_wall_app.MainLoop()
